name: Fetcher

on:
  push:
  schedule:
    - cron: '0 15 * * *'

jobs:
  fetch:
    name: rfcsubseries data fetching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/bibxml-data-misc
          path: bibxml-data-misc
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install gem
        run: |
          gem install relaton-ietf
      - name: Fetch documents
        run: |
          rm -rf data
          ruby converter.rb
      - name: Push data
        run: |
          echo `date` > flag.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data flag.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
